### ISSUE TITLE
Import error: from textblob.packages import nltk

### ISSUE THREAD

**Issue by ddorian** [sloria/textblob-aptagger#5]
On Active-python 2.7 (windows 32bit).

After doing:

pip install -U textblob
python -m textblob.download_corpora
pip install -U textblob-aptagger

The import fails on 

Traceback (most recent call last):

  from textblob_aptagger import PerceptronTagger
  File "C:\Python27\lib\site-packages\textblob_aptagger__init__.py", line 8, in <module>
    from textblob_aptagger.taggers import PerceptronTagger
  File "C:\Python27\lib\site-packages\textblob_aptagger\taggers.py", line 10, in <module>
    from textblob.packages import nltk
ImportError: No module named packages

**Comment by sloria** [comment]
For compatibility with textblob 0.9.0, you will need to install the latest development version of textblob-aptagger:

```
$ pip install -U git+https://github.com/sloria/textblob-aptagger.git@dev
```

**Comment by ddorian** [comment]
Thanks, now it works. Can you release a new version ?

**Comment by ddorian** [comment]
You think it's a good idea to also change:

`from textblob_aptagger.taggers import PerceptronTagger`
to
`from .taggers import PerceptronTagger`

in **init**.py, so it works with just copy-paste of the project folder (without installation).

The same is for line 12 on taggers.py:

`from ._perceptron import AveragedPerceptron`

If you want I can make a pull-request?

**Comment by sloria** [comment]
There are a few things that need to be addressed before the next release. For now, you can install the latest dev version with the command above or put the following in a requirements.txt file:

```
git+https://github.com/sloria/textblob-aptagger.git@dev
```

Full import are preferred. They make it easier to understand where modules and symbols come from. It is not recommended to vendorize this project. Better to install with pip using the methods I've described above.

**Comment by SarvagyaVaish** [comment]
Another option is to install nltk and then change "**from textblob.packages import nltk**" to "**import nltk**"

**Comment by tastyminerals** [comment]
Just installed TextBlob and looks like this issue is not fixed:
  ```
File "/usr/lib/python2.7/site-packages/textblob_aptagger/__init__.py", line 8, in <module>
    from textblob_aptagger.taggers import PerceptronTagger
  File "/usr/lib/python2.7/site-packages/textblob_aptagger/taggers.py", line 10, in <module>
    from textblob.packages import nltk
ImportError: No module named packages
```
